# Generated by Django 4.2.1 on 2023-06-12 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_role_description_alter_task_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.ForeignKey(default='Unassigned', on_delete=django.db.models.deletion.SET_DEFAULT, to='core.role'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='task',
            field=models.ForeignKey(default='Unassigned', on_delete=django.db.models.deletion.SET_DEFAULT, to='core.task'),
        ),
    ]
